defaults:
  - _self_
  - data/default
  - model/lassonet
  - experiment/default

study: ukb
split_dir: /trinity/home/s.mishra/test2/ac_split
node_index: 19 
gwas_node_index: node_index
fold_index: 0

